### PR TITLE
Add up highscore funtionality & Get highscore function implemented

### PR DESCRIPTION
**Pull request by lephleg**
Hey there,

I'm working on a personal project on which only one score record exists and users earn points by various events which sum up to create a ranking list.

I was glad I found your enabler as a base. However, this specific functionalities were missing so I took the chance to fork your repo and implement them.

> **API changes:**
> [leaderboard-enabler-API-changes.pdf](https://github.com/fi-content2-games-platform/FIcontent.Gaming.Enabler.Leaderboard/files/121865/leaderboard-enabler-API-changes.pdf)

My current approach supports only highscores to add up. This could be extended in the future to cover additional scores also.

This was intended for my personal needs but please feel free to review the changes and accept this pull request if you'd like. 

Any suggestions are welcome also.

My best,
lephleg

_PS: Additionally I'm working on a boostrap demo right now for testing the API. I'm going to update it in the following days._

### CODE REVIEW

**Comment by lephleg** [comment]
I've just saw that @thomasv had also suggested the **sum/add up score** functionality in an older pull request but with a seperate updateScore() function. 

You had rejected his approach by implementing the `onlyKeepBestEntry` game option, which is more elegant as an approach but unfortunately only fulfills half of the requirements set. It updates the current highscore **by replacing it with the new one if it new one is higher**. It doesn't seem to add them up.

I filled this gap by introducing the `addUpScore` game option, which extends `onlyKeepBestEntry` **by replacing the current highscore with the sum of current and new record**. 

I think its a required feature in many scenarios, so It shouldn't be missed.

I'm up for openly discuss this, if you think my code lacks in any way, so we can improve it.

lephleg

**Comment by vaifrax** [comment]
thanks lephleg!

**Comment by GiovanniFrigo** [comment]
This feature would be really nice to have, thanks @lephleg for your contribution! 

However I still see a 7-months old docker image on https://hub.docker.com/r/fic2/leaderboard/ .
Is this project still maintained by anyone?

**Comment by lephleg** [comment]
Glad to meet you, GiovanniFrigo.

I've reported the docker image issue here 

https://github.com/fi-content2-games-platform/FIcontent.Gaming.Enabler.Leaderboard/issues/8

some time ago. However it hasn't been resolved yet.

For now you can use the image I used back then If you'd like. It includes the latest changes I describe at this topic.

You can find it here:

https://hub.docker.com/r/lephleg/ficontent.gaming.enabler.leaderboard/

Regards,

**Comment by GiovanniFrigo** [comment]
Thanks @lephleg!

I will surely use your docker image in place of the old one, I didn't searched it in docker's hub in the first place :)

Thanks again!

**Pull request merged**
